[2022-07-09 15:20:51,909] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2022-07-09T15:20:50.994526+00:00 [queued]>
[2022-07-09 15:20:51,923] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2022-07-09T15:20:50.994526+00:00 [queued]>
[2022-07-09 15:20:51,924] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-09 15:20:51,925] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-09 15:20:51,925] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-09 15:20:51,949] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-07-09 15:20:50.994526+00:00
[2022-07-09 15:20:51,958] {standard_task_runner.py:52} INFO - Started process 8135 to run task
[2022-07-09 15:20:51,964] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'manual__2022-07-09T15:20:50.994526+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp42mh4fqr', '--error-file', '/tmp/tmpaf4meyd_']
[2022-07-09 15:20:51,965] {standard_task_runner.py:80} INFO - Job 33: Subtask create_table
[2022-07-09 15:20:52,054] {task_command.py:369} INFO - Running <TaskInstance: user_processing.create_table manual__2022-07-09T15:20:50.994526+00:00 [running]> on host 3e3038753a11
[2022-07-09 15:20:52,161] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-07-09T15:20:50.994526+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-09T15:20:50.994526+00:00
[2022-07-09 15:20:52,181] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-07-09 15:20:52,189] {dbapi.py:208} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users(
                users_id INT NOT NULL PRIMARY KEY,
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL UNIQUE,
                password TEXT NOT NULL,
                email TEXT NOT NULL UNIQUE
            );
            , parameters: None
[2022-07-09 15:20:52,192] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2022-07-09 15:20:52,216] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20220709T152050, start_date=20220709T152051, end_date=20220709T152052
[2022-07-09 15:20:52,260] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-09 15:20:52,315] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
